# Generated by Django 4.2.18 on 2025-02-07 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='deleted',
            new_name='deletedfile',
        ),
    ]
