# Generated by Django 4.2.18 on 2025-01-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_icon_file_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_processing_thumbnail',
            field=models.BooleanField(default=False),
        ),
    ]
